"""
Builds basketball_recruits_2026/2027/2028.csv from recruiting data.

High school recruits don't have ESPN athlete IDs until enrollment.
We use a deterministic placeholder ID format: hs{year}_{slug}
where slug is a normalized version of the player name.

Update the recruit lists below when new commits are announced
or rankings change, then re-run to regenerate the CSVs.

Usage:
    python build_bball_recruit_csvs.py
    python build_bball_recruit_csvs.py --year 2026
    python build_bball_recruit_csvs.py --dry-run
"""

import csv
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

POSITION_MAP = {
    "PG": "PG", "SG": "SG", "SF": "SF", "PF": "PF", "C": "C",
    "CG": "SG", "GF": "SF", "FC": "PF", "G": "SG", "F": "SF",
}


def composite_to_stars(composite: float) -> int:
    if composite >= 0.9900: return 5
    if composite >= 0.8900: return 4
    if composite >= 0.7900: return 3
    return 2


def make_espn_id(year: int, name: str) -> str:
    slug = re.sub(r"[^a-z0-9]", "_", name.lower().strip())
    slug = re.sub(r"_+", "_", slug).strip("_")
    return f"hs{year}_{slug}"


def normalize_position(pos: str) -> str:
    return POSITION_MAP.get(pos.upper(), "SF")


# ── 2026 RECRUITS (259 — scraped from 247Sports April 2026) ────────────────────
RECRUITS_2026 = [
    ("Tyran Stokes",                  "SF", 1.0000, "kansas"),
    ("Cameron Williams",              "PF", 0.9992, "duke"),
    ("Jordan Smith Jr.",              "PG", 0.9991, "arkansas"),
    ("Caleb Holt",                    "SG", 0.9988, "arizona"),
    ("Dylan Mingo",                   "PG", 0.9981, ""),
    ("Christian Collins",             "PF", 0.9979, "usc"),
    ("Jason Crowe Jr.",               "PG", 0.9975, "missouri"),
    ("Bruce Branch III",              "SF", 0.9974, "byu"),
    ("Anthony Thompson",              "SF", 0.9971, "ohio-state"),
    ("Deron Rippey Jr.",              "PG", 0.9965, "duke"),
    ("Baba Oladotun",                 "SF", 0.9962, "maryland"),
    ("Bryson Howard",                 "SG", 0.9953, "duke"),
    ("Caleb Gaskins",                 "PF", 0.9953, "miami"),
    ("Brandon McCoy Jr.",             "SG", 0.9950, "michigan"),
    ("Adonis Ratliff",                "PF", 0.9946, "usc"),
    ("JJ Andrews",                    "SF", 0.9941, "arkansas"),
    ("Arafan Diane",                  "C",  0.9940, "houston"),
    ("Taylen Kinney",                 "PG", 0.9939, "kansas"),
    ("Darius Ratliff",                "C",  0.9928, "usc"),
    ("Toni Bryant",                   "PF", 0.9923, "missouri"),
    ("Maximo Adams",                  "SF", 0.9921, "north-carolina"),
    ("Abdou Toure",                   "SF", 0.9919, "arkansas"),
    ("Miles Sadler",                  "PG", 0.9914, "west-virginia"),
    ("Colben Landrew",                "SF", 0.9913, "uconn"),
    ("Qayden Samuels",                "SF", 0.9910, "alabama"),
    ("Jasiah Jervis",                 "SG", 0.9899, "michigan-state"),
    ("Jaxon Richardson",              "SF", 0.9891, "alabama"),
    ("Austin Goosby",                 "PG", 0.9888, "texas"),
    ("Latrell Allmond",               "PF", 0.9886, "oklahoma-state"),
    ("Ethan Taylor",                  "C",  0.9885, "michigan-state"),
    ("Quinn Costello",                "PF", 0.9879, "michigan"),
    ("Miikka Muurinen",               "PF", 0.9877, ""),
    ("DaKari Spear",                  "SG", 0.9872, "texas-tech"),
    ("Cameron Holmes",                "SF", 0.9871, "arizona"),
    ("Tajh Ariza",                    "SF", 0.9865, "oregon"),
    ("Elijah Williams",               "SF", 0.9864, "baylor"),
    ("Chase Foster",                  "PF", 0.9860, "pittsburgh"),
    ("Lincoln Cosby",                 "SF", 0.9860, "michigan"),
    ("Alex Constanza",                "SF", 0.9859, ""),
    ("Bo Ogden",                      "SF", 0.9855, "texas"),
    ("Ikenna Alozie",                 "PG", 0.9852, "houston"),
    ("Kaden House",                   "PG", 0.9847, "maryland"),
    ("Christopher Washington Jr.",    "SF", 0.9847, ""),
    ("Anthony Felesi",                "SF", 0.9844, ""),
    ("Quincy Wadley",                 "SG", 0.9840, ""),
    ("Luke Ertel",                    "PG", 0.9837, "purdue"),
    ("Junior County",                 "SG", 0.9836, "uconn"),
    ("Luca Foster",                   "SF", 0.9835, "gonzaga"),
    ("Adam Oumiddoch",                "SG", 0.9814, "villanova"),
    ("Tarris Bouie",                  "SF", 0.9813, "alabama"),
    ("Vaughn Karvala",                "SF", 0.9813, "indiana"),
    ("Carlos Medlock Jr.",            "PG", 0.9812, "michigan-state"),
    ("Ralph Scott",                   "SF", 0.9801, "tennessee"),
    ("Kayden Allen",                  "SF", 0.9801, "georgia-tech"),
    ("Davion Adkins",                 "C",  0.9798, "kansas"),
    ("Joe Philon",                    "PF", 0.9798, "ucla"),
    ("Aiden Derkack",                 "SG", 0.9798, ""),
    ("Lucas Morillo",                 "SG", 0.9791, "illinois"),
    ("Marcis Ponder",                 "C",  0.9788, "florida-state"),
    ("Sammy Jackson",                 "SF", 0.9786, ""),
    ("Dean Rueckert",                 "SF", 0.9772, "byu"),
    ("Aziz Olajuwon",                 "SF", 0.9770, "stanford"),
    ("Jacob Webber",                  "SF", 0.9770, "purdue"),
    ("Gavin Placide",                 "PF", 0.9769, "wake-forest"),
    ("Tristan Reed",                  "C",  0.9756, "mississippi-state"),
    ("Josh Irving",                   "C",  0.9756, "texas-am"),
    ("Martay Barnes",                 "PG", 0.9754, "florida-state"),
    ("Ethan Mgbako",                  "SF", 0.9753, "vanderbilt"),
    ("Marcus Johnson",                "PG", 0.9741, "south-carolina"),
    ("Sinan Huan",                    "C",  0.9741, "purdue"),
    ("Jonathan Sanderson",            "PG", 0.9740, "notre-dame"),
    ("Gage Mayfield",                 "PF", 0.9738, "oklahoma"),
    ("Katrelle Harmon",               "PG", 0.9736, "creighton"),
    ("Jalen Montonati",               "SF", 0.9733, "oklahoma-state"),
    ("Anthony Brown",                 "PG", 0.9723, "vanderbilt"),
    ("Darius Bivins",                 "PG", 0.9721, ""),
    ("Jayden Hodge",                  "SF", 0.9715, "northwestern"),
    ("Kalek House",                   "SG", 0.9713, "xavier"),
    ("Joseph Hartman",                "SG", 0.9707, "michigan"),
    ("Colin Rice",                    "SF", 0.9706, "nebraska"),
    ("Julius Avent",                  "PF", 0.9703, "michigan-state"),
    ("Alex Egbuonu",                  "SF", 0.9700, "marquette"),
    ("Willie Burnett III",            "PG", 0.9676, "mississippi-state"),
    ("Kevin Thomas",                  "SF", 0.9675, "lsu"),
    ("Cole Cloer",                    "SF", 0.9674, "nc-state"),
    ("Dorian Rinaldo-Komlan",         "C",  0.9668, "iowa-state"),
    ("Fred Smith Jr.",                "PF", 0.9666, "memphis"),
    ("Trey Beamer",                   "PG", 0.9666, "boston-college"),
    ("Christian Gibson",              "SF", 0.9661, "ucf"),
    ("Jacob Lanier",                  "SG", 0.9649, "nebraska"),
    ("Quentin Coleman",               "SG", 0.9646, "illinois"),
    ("Trent Perry",                   "SF", 0.9641, "kansas"),
    ("Jermal Jones",                  "SG", 0.9636, "pittsburgh"),
    ("Felipe Quinones",               "PG", 0.9620, ""),
    ("Preston Wade",                  "PF", 0.9609, ""),
    ("Joe Sterling",                  "PG", 0.9604, "texas"),
    ("Jackson Sheffield",             "C",  0.9600, "vanderbilt"),
    ("Herly Brutus",                  "SF", 0.9587, "butler"),
    ("Boyuan Zhang",                  "SF", 0.9562, ""),
    ("Trevor Manhertz",               "SF", 0.9547, "indiana"),
    ("Nolen Anderson",                "SF", 0.9532, "minnesota"),
    ("Rider Portela",                 "SF", 0.9528, "colorado"),
    ("Sam Funches",                   "C",  0.9512, "gonzaga"),
    ("Jaen Chatman",                  "PG", 0.9511, ""),
    ("Prince-Alexander Moody",        "PG", 0.9504, "indiana"),
    ("Cody Peck",                     "C",  0.9487, ""),
    ("Maxime Meyer",                  "C",  0.9486, "duke"),
    ("Gallagher Placide",             "PF", 0.9479, "wake-forest"),
    ("Isaiah Rogers",                 "PG", 0.9479, "stanford"),
    ("Dreylan Creasy",                "SF", 0.9478, ""),
    ("Brandon Bass Jr.",              "SG", 0.9463, "florida-state"),
    ("Ethan Harris",                  "PF", 0.9451, "iowa"),
    ("Moustapha Diop",                "C",  0.9448, ""),
    ("Collin Paul",                   "SF", 0.9447, "florida-state"),
    ("Jackson Kiss",                  "C",  0.9446, "iowa-state"),
    ("Jaidyn Coon",                   "SF", 0.9444, "iowa"),
    ("Ethan Brown",                   "PG", 0.9444, "illinois"),
    ("Trevon Carter-Givens",          "C",  0.9437, "nc-state"),
    ("Jaroslavs Pihtovs",             "C",  0.9435, ""),
    ("Jalyn Collingwood",             "SF", 0.9434, "mississippi-state"),
    ("Asher Elson",                   "PF", 0.9434, "xavier"),
    ("Collin Ross",                   "PF", 0.9420, ""),
    ("Alex Smith",                    "PF", 0.9414, "ohio-state"),
    ("Harris Reynolds",               "SG", 0.9412, "clemson"),
    ("Mason Williams",                "PG", 0.9408, "kentucky"),
    ("Aidan Chronister",              "SF", 0.9407, "missouri"),
    ("Eli Sancomb",                   "PG", 0.9401, ""),
    ("Yabi Aklog",                    "C",  0.9397, ""),
    ("Parker Robinson",               "SG", 0.9389, "oklahoma-state"),
    ("Adama Tambedou",                "PF", 0.9389, "maryland"),
    ("Christian Wiggins",             "SG", 0.9385, "iowa-state"),
    ("Luke Barnett",                  "SG", 0.9383, "kansas"),
    ("Chidi Nwigwe",                  "SF", 0.9374, ""),
    ("Jasen Lopez",                   "PG", 0.9373, "florida-state"),
    ("Shane Pendergrass",             "PF", 0.9370, ""),
    ("Will Stevens",                  "C",  0.9368, "clemson"),
    ("Manny Green",                   "PF", 0.9360, "tennessee"),
    ("JRob Croy",                     "PG", 0.9356, "arizona-state"),
    ("Aliou Dioum",                   "C",  0.9349, "west-virginia"),
    ("Noah Smith",                    "PF", 0.9336, "depaul"),
    ("Favour Ibe",                    "C",  0.9324, ""),
    ("Kendre Harrison",               "C",  0.9318, "oregon"),
    ("Brady Hennig",                  "SG", 0.9318, ""),
    ("Donovan Criss",                 "SF", 0.9312, ""),
    ("Gan-Erdene Solongo",            "C",  0.9307, "notre-dame"),
    ("Chadrack Mpoyi",                "C",  0.9302, "minnesota"),
    ("Braylen Langley",               "PF", 0.9297, ""),
    ("Landyn Colyer",                 "SG", 0.9285, ""),
    ("Cam Lomax",                     "PG", 0.9284, "smu"),
    ("Landon Davis",                  "PF", 0.9268, "illinois"),
    ("Josiah Johnson",                "PG", 0.9268, ""),
    ("Marcus Gillespie",              "SG", 0.9265, ""),
    ("MJ Madison",                    "PF", 0.9259, ""),
    ("Ryan Kreager",                  "C",  0.9257, ""),
    ("Torrey Brooks Jr.",             "PG", 0.9257, ""),
    ("Ryan Moesch",                   "PG", 0.9252, "syracuse"),
    ("Javonte Floyd",                 "C",  0.9229, "ucla"),
    ("Mason Fuentes",                 "PG", 0.9204, ""),
    ("Jack Kayil",                    "PG", 0.9200, "gonzaga"),
    ("Mark Morano Mahmutovic",        "SF", 0.9200, "syracuse"),
    ("Julius Price",                  "SG", 0.9191, "stanford"),
    ("Jalan Wingfield",               "PF", 0.9169, ""),
    ("Elias Obenyah",                 "PG", 0.9165, "stanford"),
    ("Jason Singleton",               "PG", 0.9160, ""),
    ("SJ Madison",                    "SF", 0.9159, ""),
    ("Trey Pearson",                  "PG", 0.9156, ""),
    ("Darien Moore",                  "PG", 0.9156, "seton-hall"),
    ("Tyshawn Duncan",                "C",  0.9153, ""),
    ("Jahda Swann",                   "SG", 0.9153, ""),
    ("Dionte Neal",                   "PG", 0.9151, ""),
    ("Marcus Vaughns",                "SF", 0.9150, "lsu"),
    ("Kaiden Bailey",                 "PG", 0.9144, ""),
    ("Keriawn Berry",                 "SF", 0.9142, ""),
    ("Steven Reynolds",               "SG", 0.9140, ""),
    ("Jaden Ghoreishi",               "C",  0.9137, ""),
    ("Yohance Connor",                "PG", 0.9136, "ole-miss"),
    ("Jermel Thomas",                 "PG", 0.9132, ""),
    ("Zamir Paschal",                 "PG", 0.9118, ""),
    ("Lincoln Williams",              "SF", 0.9112, ""),
    ("Nasir Price",                   "SG", 0.9109, ""),
    ("Jaylen Alexander",              "PG", 0.9108, "kansas-state"),
    ("Justin Caldwell",               "PF", 0.9107, "georgetown"),
    ("Cello Jackson",                 "SF", 0.9105, "memphis"),
    ("Jordan Sigmon",                 "PG", 0.9104, ""),
    ("TJ Crumble",                    "PF", 0.9098, ""),
    ("Brannon Martinsen",             "SF", 0.9097, ""),
    ("Drew Anderson",                 "PF", 0.9097, "stanford"),
    ("Andrew Hilman",                 "SG", 0.9094, ""),
    ("Xavier Blake",                  "SG", 0.9093, ""),
    ("Adam Tyson",                    "SF", 0.9092, ""),
    ("Jamyn Sondrup",                 "C",  0.9089, "purdue"),
    ("Jaron Saulsberry",              "SF", 0.9085, "ole-miss"),
    ("Kobe Edwards",                  "PG", 0.9081, ""),
    ("Jordan Skyers",                 "PG", 0.9067, ""),
    ("Ethan Johnston",                "SG", 0.9066, "marquette"),
    ("Dionycius Bakare",              "SF", 0.9065, "cal"),
    ("Malachi Brown",                 "SF", 0.9063, "michigan"),
    ("Yusef Gray Jr.",                "PG", 0.9061, "iowa-state"),
    ("Mason Magee",                   "PG", 0.9058, ""),
    ("Ashton Meeks",                  "PG", 0.9057, ""),
    ("Seven Spurlock",                "SF", 0.9045, "oregon"),
    ("Keonte Greybear",               "PG", 0.9043, ""),
    ("Franck Belibi",                 "SG", 0.9043, ""),
    ("Imahri Wooten",                 "SF", 0.9038, "rutgers"),
    ("Kingston Whitty",               "PG", 0.9037, ""),
    ("Korie Corbett",                 "SF", 0.9037, ""),
    ("Bradley Floyd",                 "SG", 0.9037, ""),
    ("Kamai Samuels",                 "PG", 0.9036, ""),
    ("Dothan Ijadimbola",             "SF", 0.9035, ""),
    ("LaTrevion Fenderson",           "SF", 0.9034, "wisconsin"),
    ("Isaiah Wilks",                  "PG", 0.9032, ""),
    ("Sam Fleming",                   "PF", 0.9031, ""),
    ("Desmond Bellot",                "SG", 0.9028, ""),
    ("Eric Hillsman",                 "SF", 0.9027, ""),
    ("Pops Dunson",                   "PG", 0.9027, ""),
    ("Symon Ghai",                    "C",  0.9025, "northwestern"),
    ("Cole Edelen",                   "PG", 0.9016, ""),
    ("Elhadji Diallo",                "PF", 0.9014, ""),
    ("Caleb Williams",                "SG", 0.9010, "auburn"),
    ("Lattimore Ford",                "SF", 0.9009, ""),
    ("Donovan Williams",              "PG", 0.9008, "ucf"),
    ("Jaxson Thompson",               "PG", 0.9008, ""),
    ("Gabe Weis",                     "SF", 0.9004, ""),
    ("Aeneas Alexander",              "PF", 0.9004, ""),
    ("Austin Brown",                  "PF", 0.9004, "maryland"),
    ("Eric Fiedler",                  "PF", 0.9003, ""),
    ("Hassan Koureissi",              "SG", 0.9002, ""),
    ("Manu Manciel",                  "SG", 0.9002, ""),
    ("Jayson Peterson",               "PF", 0.9001, ""),
    ("Daniel Patton",                 "PF", 0.9000, ""),
    ("Jayden Moore",                  "PG", 0.8994, ""),
    ("Devin Hutcherson",              "SG", 0.8992, "kansas-state"),
    ("Kuol Deng",                     "C",  0.8989, ""),
    ("Derrick Morton-Rivera",         "SG", 0.8985, ""),
    ("Ladarius Givan",                "C",  0.8984, ""),
    ("Jaxson Terry",                  "SF", 0.8982, ""),
    ("Zavier Zens",                   "PF", 0.8980, ""),
    ("Jayden Johnson",                "SG", 0.8978, ""),
    ("Rivers Knight",                 "PF", 0.8974, "purdue"),
    ("Jamison White",                 "PF", 0.8969, "penn-state"),
    ("Jasiah Cannady",                "PG", 0.8969, ""),
    ("Julian Washington",             "SG", 0.8966, ""),
    ("Ashton Pierce",                 "SG", 0.8960, ""),
    ("Mani Sajid",                    "SG", 0.8958, ""),
    ("Kota Suttle",                   "PG", 0.8951, ""),
    ("Zach White",                    "SF", 0.8950, "san-diego-state"),
    ("Styles Clemmons",               "PG", 0.8947, "utah"),
    ("Brayden Kyman",                 "PF", 0.8945, ""),
    ("Hakeem Weems",                  "C",  0.8944, ""),
    ("Josiah Sanders",                "PF", 0.8933, ""),
    ("Tyus Thomas",                   "PG", 0.8933, ""),
    ("Martechio Hayes",               "SG", 0.8931, ""),
    ("Keeper Jackson",                "PF", 0.8927, ""),
    ("Marquis Clark",                 "PG", 0.8926, "tennessee"),
    ("Gabriel Sularski",              "SF", 0.8922, ""),
    ("Chris Powell",                  "SG", 0.8910, ""),
    ("Dikembe Shaw",                  "PF", 0.8910, ""),
    ("Aaron McGee",                   "SG", 0.8906, ""),
    ("Amare James",                   "SG", 0.8900, "clemson"),
]


# ── 2027 RECRUITS (210 — scraped from 247Sports April 2026) ────────────────────
RECRUITS_2027 = [
    ("CJ Rosser",                     "PF", 0.9995, ""),
    ("Obinna Ekezie Jr.",             "C", 0.9988, ""),
    ("Ryan Hampton",                  "SF", 0.9987, ""),
    ("Marcus Spears Jr.",         "PF", 0.9987, ""),
    ("Paul Osaruyi",              "C",  0.9979, ""),
    ("Moussa Kamissoko",          "SF", 0.9975, ""),
    ("Nasir Anderson",            "PG", 0.9970, ""),
    ("Beckham Black",             "PG", 0.9969, ""),
    ("Jordan Page",               "SG", 0.9969, ""),
    ("King Gibson",               "SG", 0.9961, ""),
    ("Dawson Battie",             "PF", 0.9954, ""),
    ("Malachi Jordan",            "SF", 0.9951, ""),
    ("Isaiah Hill",               "C",  0.9939, ""),
    ("Reese Alston",              "PG", 0.9938, ""),
    ("Demarcus Henry",            "SF", 0.9937, ""),
    ("Cayden Daughtry",           "PG", 0.9930, ""),
    ("Gabe Nesmith",              "SF", 0.9930, ""),
    ("Darius Wabbington",         "C",  0.9927, ""),
    ("Jalen Davis",               "SG", 0.9922, ""),
    ("Josh Leonard",              "SF", 0.9922, ""),
    ("Javon Bardwell",            "SF", 0.9915, "kansas"),
    ("Zion Green",                "PF", 0.9911, ""),
    ("NaVorro Bowman Jr.",        "SG", 0.9907, ""),
    ("Davion Thompson",           "PG", 0.9907, ""),
    ("Jeremy Jenkins",            "PF", 0.9905, ""),
    ("Dooney Johnson",            "SF", 0.9902, ""),
    ("Anderson Diaz",             "PG", 0.9889, ""),
    ("RJ Moore",                  "SG", 0.9888, ""),
    ("Ahmad Hudson",              "PF", 0.9888, ""),
    ("Devin Cleveland",           "PG", 0.9886, ""),
    ("Donovan Davis",             "PF", 0.9884, ""),
    ("Tyran Frazier",             "C",  0.9882, ""),
    ("LJ Smith",                  "SG", 0.9879, ""),
    ("Jason Gardner Jr.",         "SG", 0.9873, ""),
    ("Jarvis Hayes Jr.",          "SG", 0.9872, ""),
    ("Gene Roebuck",              "SF", 0.9865, ""),
    ("Munir Greig",               "SF", 0.9862, ""),
    ("Chase Branham",             "PG", 0.9862, ""),
    ("Scottie Adkinson",          "SG", 0.9860, ""),
    ("Jaylan Mitchell",           "PF", 0.9859, ""),
    ("Micah Gordon",              "PG", 0.9850, ""),
    ("Theo Edema",                "C",  0.9843, ""),
    ("Tyrone Jamison",            "PG", 0.9842, ""),
    ("Henry Robinson",            "SF", 0.9839, ""),
    ("Oneal Delancy",             "SG", 0.9839, ""),
    ("Cherif Millogo",            "C",  0.9837, ""),
    ("Ahmed Nur",                 "PF", 0.9837, ""),
    ("Howard Williams",           "SF", 0.9835, ""),
    ("Kevin Savage",              "PG", 0.9829, ""),
    ("Josiah Harrington",         "SF", 0.9829, ""),
    ("Jaxson Davis",              "PG", 0.9825, ""),
    ("Carson Crawford",           "SF", 0.9821, ""),
    ("Brandon Woodard",           "PF", 0.9817, ""),
    ("Antonio Pemberton",         "PG", 0.9807, ""),
    ("Dylan Jones",               "SF", 0.9800, ""),
    ("Chase Lumpkin",             "SG", 0.9797, ""),
    ("Mahamadou Diop",            "C",  0.9797, ""),
    ("Jomar Bernard",             "SF", 0.9796, ""),
    ("J'Lon Lyons",               "PG", 0.9795, ""),
    ("Patrick Otey",              "SG", 0.9794, ""),
    ("Baboucarr Ann",             "SF", 0.9782, ""),
    ("Jack Kohnen",               "SF", 0.9782, ""),
    ("Jahari Miller",             "SG", 0.9765, ""),
    ("Asa Montgomery",            "SF", 0.9756, ""),
    ("Mekhi Robertson",           "SG", 0.9743, ""),
    ("Aaron Britt Jr.",           "PG", 0.9735, ""),
    ("Nicolas Mitrovic",          "C",  0.9735, ""),
    ("Clyde Walters",             "SF", 0.9724, ""),
    ("Kamsi Awaka",               "C",  0.9722, ""),
    ("Darrell Davis",             "PG", 0.9721, ""),
    ("Jalen Brown",               "SG", 0.9721, ""),
    ("Chase Richardson",          "PG", 0.9721, ""),
    ("Jeremiah Profit",           "SF", 0.9705, ""),
    ("Caleb Ourigou",             "C",  0.9705, ""),
    ("Joshua Rivera",             "SG", 0.9704, ""),
    ("Cameron Barnes",            "PF", 0.9695, ""),
    ("Joshua Tyson",              "SG", 0.9689, ""),
    ("Payton Jones",              "PG", 0.9684, ""),
    ("Kager Knueppel",            "PF", 0.9680, ""),
    ("Keaundre Morris",           "PG", 0.9674, ""),
    ("Miguel Orbe",               "SG", 0.9673, ""),
    ("Derek Daniels",             "C",  0.9665, ""),
    ("Andrew Kretkowski",         "SF", 0.9662, ""),
    ("Lyris Robinson",            "SG", 0.9655, ""),
    ("Quincy Douby Jr.",          "SG", 0.9650, ""),
    ("Crew Fotheringham",         "SF", 0.9650, ""),
    ("Jalen White",               "SF", 0.9645, ""),
    ("Godson Okokoh",             "PF", 0.9644, ""),
    ("Tre Keith",                 "SG", 0.9642, ""),
    ("Isaiah Santos",             "SF", 0.9642, ""),
    ("Brian Mitchell Jr.",        "SF", 0.9640, ""),
    ("Chris Brown",               "C",  0.9639, ""),
    ("Ferlandes Wright",          "PF", 0.9636, "louisville"),
    ("Jaydn Jenkins",             "C",  0.9635, ""),
    ("Lewis Uvwo",                "C",  0.9627, ""),
    ("Marri Wesley",              "SF", 0.9619, ""),
    ("Justin Wise",               "SG", 0.9613, ""),
    ("Myles Fuentes",             "PG", 0.9610, ""),
    ("Thomas Vickery",            "SF", 0.9602, ""),
    ("Josiah Nance",              "SG", 0.9592, ""),
    ("Jacques Mitchell",          "SG", 0.9586, ""),
    ("Ty Schlagel",               "SF", 0.9586, ""),
    ("London Dada",               "SF", 0.9572, ""),
    ("Malcolm Price",             "SG", 0.9570, ""),
    ("Deuce McDuffie",            "SF", 0.9565, ""),
    ("Markus Kerr",               "SG", 0.9560, ""),
    ("Charles Pur",               "C",  0.9558, ""),
    ("Bryce Curry",               "SG", 0.9557, ""),
    ("Jacob Canton",              "PG", 0.9555, ""),
    ("Jacoby Briscoe",            "SF", 0.9555, ""),
    ("Kameron Cooper",            "SF", 0.9537, ""),
    ("Jordan Hunter",             "SG", 0.9534, ""),
    ("Marlon Martinez",           "SG", 0.9533, ""),
    ("Kellen Brewer",             "SG", 0.9526, ""),
    ("Frashad Tisby",             "SF", 0.9523, ""),
    ("Deshawn Dillon",            "SG", 0.9515, ""),
    ("Declan Griffiths",          "SF", 0.9511, ""),
    ("Mustafa Mohamed",           "PF", 0.9510, ""),
    ("Joaquim Boumtje Boumtje",   "C",  0.9500, ""),
    ("LJ Diamond",                "SG", 0.9495, ""),
    ("Lucai Anderson",            "SG", 0.9486, ""),
    ("Nick Welch Jr.",            "C",  0.9475, ""),
    ("Will Davis",                "SF", 0.9456, ""),
    ("Sekou Cisse",               "C",  0.9455, ""),
    ("David Conerly",             "SF", 0.9446, ""),
    ("Kamari Whyte",              "SG", 0.9442, ""),
    ("DJ Hawkins",                "SF", 0.9441, ""),
    ("Jimmie Haywood",            "SG", 0.9427, ""),
    ("Zaahir Muhammad-Gray",      "PF", 0.9414, ""),
    ("Griffin Starks",            "PF", 0.9412, ""),
    ("Josiah Adamson",            "SG", 0.9410, ""),
    ("Gassim Toure",              "PG", 0.9408, ""),
    ("Dylan Cowell",              "PF", 0.9402, ""),
    ("Eden Vinyard",              "PF", 0.9395, ""),
    ("Archie Weatherspoon",       "PG", 0.9391, ""),
    ("Luke Howery",               "SG", 0.9390, ""),
    ("Ty Cobb",                   "SG", 0.9382, ""),
    ("Templeton Fountaine V",     "SG", 0.9382, ""),
    ("Trevor Dickson",            "SG", 0.9373, ""),
    ("Steven McLeod",             "PF", 0.9373, ""),
    ("Andrew Ross",               "SG", 0.9365, ""),
    ("Zain Majeed",               "PF", 0.9357, ""),
    ("Braxton Keathley",              "PG", 0.9355, ""),
    ("Kavian Bryant",                 "PG", 0.9348, ""),
    ("Malik Parrish",                 "PF", 0.9329, ""),
    ("Corey Dixon",                   "PG", 0.9327, ""),
    ("Damon Miles",                   "PG", 0.9325, ""),
    ("Nolan Nelson",                  "PF", 0.9321, ""),
    ("Davey Harris",                  "SF", 0.9317, ""),
    ("EJ Popoola",                    "SF", 0.9313, ""),
    ("Peyton Kemp",                   "PG", 0.9301, ""),
    ("Cadarian Urune",                "SG", 0.9293, ""),
    ("Ajani Stewart",                 "SG", 0.9289, ""),
    ("Precious Sam",                  "C",  0.9281, ""),
    ("Jamaal McKnight Jr.",           "PG", 0.9273, ""),
    ("Christopher Hunt Jr.",          "PG", 0.9273, ""),
    ("Cooper Zachary",                "PG", 0.9269, ""),
    ("Braelon Bradshaw",              "SF", 0.9265, ""),
    ("Brandon Mason Jr.",             "SG", 0.9261, ""),
    ("Landon Evans",                  "SG", 0.9261, ""),
    ("Fallilou Mbengue",              "C",  0.9253, ""),
    ("Quinton Kitt",                  "PF", 0.9245, "illinois"),
    ("Joessette Sanchez",             "SF", 0.9245, ""),
    ("Kingston Money",                "SG", 0.9237, ""),
    ("Amarion Hunter",                "PG", 0.9233, ""),
    ("Marquis Newson",                "SG", 0.9231, ""),
    ("Caden Ivery",                   "PG", 0.9229, ""),
    ("Lincoln Vinson",                "PG", 0.9223, ""),
    ("Daniel Abass",                  "PF", 0.9213, ""),
    ("Jymin Veney",                   "PG", 0.9209, ""),
    ("Jae Lincoln",                   "SF", 0.9205, ""),
    ("Isaiah Mack-Russell",           "SG", 0.9199, ""),
    ("Ty Newsom",                     "SF", 0.9197, ""),
    ("Xander Pruzinsky",              "PF", 0.9193, ""),
    ("Shawn Foster",                  "PG", 0.9191, ""),
    ("MJ Curry",                      "SG", 0.9189, ""),
    ("Isaac Ellis",                   "PG", 0.9187, ""),
    ("David Baliraine",               "C",  0.9187, ""),
    ("Matthew Langhi",                "SF", 0.9185, ""),
    ("Jared Jeffers",                 "C",  0.9181, ""),
    ("Jimmy McKinney III",            "PG", 0.9179, ""),
    ("Aiden Bolden",                  "PF", 0.9177, ""),
    ("Tony Cornett III",              "SG", 0.9175, ""),
    ("Brayden Williams",              "SG", 0.9173, ""),
    ("Ashton Shewell",                "PG", 0.9169, ""),
    ("Janon Singh",                   "SF", 0.9167, ""),
    ("JJ Watts",                      "PF", 0.9163, ""),
    ("Avery Moses",                   "SG", 0.9163, ""),
    ("Stevie Hall",                   "PG", 0.9161, ""),
    ("Shaq Kizzee",                   "PF", 0.9159, ""),
    ("Caleb Lundy",                   "PG", 0.9151, ""),
    ("Patrese Feamster",              "SG", 0.9139, ""),
    ("Chris Sanders",                 "SF", 0.9135, ""),
    ("Taj Saragba",                   "PF", 0.9133, ""),
    ("King Kendrick",                 "PG", 0.9122, ""),
    ("OJ Popoola",                    "SF", 0.9119, ""),
    ("Anthony Goring",                "C",  0.9097, ""),
    ("Avery Huston",                  "SG", 0.9085, ""),
    ("Bryant Robinson",               "SG", 0.9081, ""),
    ("Landon Veal",                   "PF", 0.9075, ""),
    ("Tyson Pogi",                    "PG", 0.9065, ""),
    ("Malachi Booker",                "SF", 0.9055, ""),
    ("Drew Guy",                      "PG", 0.9053, ""),
    ("Greyson Pierce",                "PF", 0.9043, ""),
    ("Ian Condon",                    "PF", 0.9027, ""),
    ("Delton Prescott",               "PG", 0.9021, ""),
    ("Charlie Cohn",                  "C",  0.9010, ""),
    ("Carson Butler",                 "PF", 0.9008, ""),
    ("Kirby Duran",                   "PG", 0.8979, ""),
]


# ── 2028 RECRUITS (81 — scraped from 247Sports April 2026) ────────────────────
RECRUITS_2028 = [
    ("AJ Williams",                   "SF", 0.9999, ""),
    ("Bamba Touray",             "C",  0.9994, ""),
    ("Colton Hiller",            "SF", 0.9992, ""),
    ("Isaiah Hamilton",          "SF", 0.9986, ""),
    ("Erick Dampier Jr.",        "C",  0.9986, ""),
    ("Bentley Lusakueno",        "C",  0.9982, ""),
    ("Adan Diggs",               "SG", 0.9979, ""),
    ("Shalen Sheppard",          "PF", 0.9973, ""),
    ("Mason Collins",            "SF", 0.9973, ""),
    ("Dylan Betts",              "C",  0.9964, ""),
    ("Kameron Mercer",           "SG", 0.9961, ""),
    ("DJ Okoth",                 "SF", 0.9959, ""),
    ("Josh Lowery",              "SG", 0.9957, ""),
    ("Myles Hayes",              "SG", 0.9944, ""),
    ("Brady Pettigrew",          "SG", 0.9940, ""),
    ("Logan Chwastyk",           "C",  0.9935, ""),
    ("Michai White",             "PG", 0.9930, ""),
    ("Xavier Young",             "C",  0.9926, ""),
    ("Jakyi Miles",              "SG", 0.9924, ""),
    ("Joshua Lindsay",           "SG", 0.9923, ""),
    ("Quinton Wilson",           "SG", 0.9920, ""),
    ("Antoine Caughman Jr.",     "SF", 0.9917, ""),
    ("Malik Moore",              "PG", 0.9916, ""),
    ("Blaze Johnson",            "PG", 0.9916, ""),
    ("Kevin Wheatley Jr.",       "SG", 0.9915, ""),
    ("Isaiah Carter",            "SF", 0.9912, ""),
    ("Tai Bell",                 "PG", 0.9910, ""),
    ("Xavier Skipworth",         "SF", 0.9906, ""),
    ("Evan Willis",              "SF", 0.9896, ""),
    ("Liam Mitakaro",            "SG", 0.9888, ""),
    ("Josiah Rose",              "SG", 0.9880, ""),
    ("Will Brunson",             "SF", 0.9879, ""),
    ("Braxton Bogard",           "PF", 0.9877, ""),
    ("Boogie Cook",              "SF", 0.9875, ""),
    ("CJ Moore",                 "SF", 0.9873, ""),
    ("Nash Avery",               "PF", 0.9872, ""),
    ("Boss Mhoon",               "SF", 0.9872, ""),
    ("Rowan Phillips",           "SG", 0.9870, ""),
    ("Anthony Spratt Jr.",       "SF", 0.9868, ""),
    ("Devaughn Dorrough",        "SF", 0.9863, ""),
    ("Peter Julius",             "C",  0.9858, ""),
    ("Cole Kelly",               "SF", 0.9854, ""),
    ("Will Nelson",              "SF", 0.9853, ""),
    ("Emmanuel Nwabuoku",        "C",  0.9852, ""),
    ("Landon Lampley",           "SF", 0.9850, ""),
    ("Trey Edwards",             "SG", 0.9847, ""),
    ("Kelvin Anderson",          "SG", 0.9847, ""),
    ("Kmajay Jenkins",           "SF", 0.9843, ""),
    ("Isaac Smith",              "SF", 0.9828, ""),
    ("Brielen Craft",            "PG", 0.9827, ""),
    ("Darren Ford",              "SG", 0.9823, ""),
    ("Tyler Sutton",             "SG", 0.9818, ""),
    ("Noah Washington",          "SG", 0.9813, ""),
    ("Kaharri Coleman",          "PG", 0.9810, ""),
    ("Benjamin Berrouet",        "PF", 0.9807, ""),
    ("Jordan Mize",              "SG", 0.9807, ""),
    ("Rezon Harris Jr.",         "SF", 0.9803, ""),
    ("Mateen Cleaves Jr.",       "SG", 0.9799, ""),
    ("Stra Zelic",               "C",  0.9793, ""),
    ("Chase Smith",              "PF", 0.9791, ""),
    ("Nijaun Harris",            "SG", 0.9775, ""),
    ("Joshua Huggins",           "SF", 0.9771, ""),
    ("Kareem Smith-Bey",         "SG", 0.9771, ""),
    ("Keaton Murry",             "SG", 0.9763, ""),
    ("Billy Stanfield III",      "SF", 0.9755, ""),
    ("Derek Swartz",             "SG", 0.9751, ""),
    ("Keonte Smith",             "SF", 0.9744, ""),
    ("Jaden McCullough",         "PG", 0.9731, ""),
    ("Carter Smith",             "SG", 0.9727, ""),
    ("Aidan Carter",             "PG", 0.9723, ""),
    ("Trey McKinney",            "SF", 0.9443, ""),
    ("Xavier Hall",              "C",  0.9403, ""),
    ("Ian Archbold",                  "PG", 0.9375, ""),
    ("Toussaint Malukila",            "C",  0.9358, ""),
    ("Devin Mitchell",                "SG", 0.9338, ""),
    ("Baer Bailey",                   "PF", 0.9335, ""),
    ("Terrell Jackson",               "C",  0.9303, ""),
    ("Mekhi Allen",                   "SG", 0.9295, ""),
    ("Dylan Zeigler",                 "PG", 0.8900, ""),
    ("Kaleb Allen",                   "SF", 0.8900, ""),
    ("Amarion Smith-Holley",          "PG", 0.8900, ""),
]


def build_csv(year: int, recruits: list, dry_run: bool = False) -> int:
    rows = []
    for name, pos_247, composite, school_slug in recruits:
        espn_id = make_espn_id(year, name)
        position = normalize_position(pos_247)
        stars = composite_to_stars(composite)
        rows.append({
            "espn_athlete_id": espn_id,
            "player_name": name,
            "star_rating": stars,
            "composite_score": round(composite, 4),
            "position_247": position,
            "committed_school_slug": school_slug,
            "hs_grad_year": year,
        })

    if dry_run:
        print(f"\n  Class of {year}: {len(rows)} recruits")
        committed = [r for r in rows if r["committed_school_slug"]]
        print(f"  Committed to our schools: {len(committed)}")
        for r in committed:
            print(
                f"    {r['player_name']:30s} | {r['position_247']:4s} | "
                f"{r['star_rating']}* | {r['composite_score']} -> {r['committed_school_slug']}"
            )
        return len(rows)

    path = os.path.join(os.path.dirname(__file__), "data", f"basketball_recruits_{year}.csv")
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "espn_athlete_id", "player_name", "star_rating",
                "composite_score", "position_247",
                "committed_school_slug", "hs_grad_year",
            ],
        )
        writer.writeheader()
        writer.writerows(rows)

    print(f"  Wrote {len(rows)} recruits -> {path}")
    return len(rows)


def main(dry_run: bool = False, year: int | None = None) -> None:
    years = {2026: RECRUITS_2026, 2027: RECRUITS_2027, 2028: RECRUITS_2028}
    if year:
        years = {year: years[year]}

    print("Building basketball recruit CSVs...")
    total = 0
    for y, recruits in sorted(years.items()):
        total += build_csv(y, recruits, dry_run)

    print(f"\nTotal: {total} recruits across {len(years)} class years")
    if not dry_run:
        print("\nNext steps:")
        print("  python ingest_bball_recruits.py")
        print("  python calculate_bball_valuations.py")
        print("  python generate_bball_slugs.py")


if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    year_arg = None
    for i, arg in enumerate(sys.argv):
        if arg == "--year" and i + 1 < len(sys.argv):
            year_arg = int(sys.argv[i + 1])
    main(dry_run=dry_run, year=year_arg)
