"""
execute_cleanup.py
-------------------
Executes the duplicate cleanup plan generated by diagnose_duplicates.py.
Runs merges (UPDATE) first, then deletes (DELETE), with verification.

Usage:
    python execute_cleanup.py
"""

import sys
sys.stdout.reconfigure(encoding="utf-8")

from supabase_client import supabase

# ─── Cleanup plan from diagnose_duplicates.py ────────────────────────────────
# Format: (team, player_name, keeper_id, delete_id, merge_fields_or_None)

CLEANUP_PLAN = [
    # Alabama
    ("Alabama", "Khalifa Keith", "8da2bc9c-d8f5-4c22-a7b7-fd68f2271a8b", "ace4ad98-0c1c-43b4-ab97-d43a2fdfd54c", None),
    ("Alabama", "Ryan Coleman-Williams", "ef047f71-2521-41ea-b69c-e15ee40ae1be", "07c4f16b-e2bd-4fd5-a469-0ec006eb4924", None),
    ("Alabama", "Keelon Russell", "eeaa707e-95c0-4399-a16c-7b3d5b512b22", "d8199379-5d1a-455e-9997-ff08c77a08c2", None),
    # Arizona State
    ("Arizona State", "Jake Fette", "9f8c0a95-133a-50db-a179-05f5bfca746c", "8fd524f6-b304-46cd-9575-e461fc8702c3", None),
    # Auburn
    ("Auburn", "Byrum Brown", None, "470c85e5-5d32-48d5-8f5e-77b987389ca5", None),
    # Clemson
    ("Clemson", "Gordon Sellars", None, "4411df2c-094e-5a76-91ce-719ab0601eb7", None),
    # Colorado
    ("Colorado", "Santana Hopper", None, "b5140267-61ff-4134-ad09-dd3cbff636cb", None),
    # Florida State
    ("Florida State", "Darryl Bell III", None, "d87b59ee-e86b-4cbf-b78f-88809fba8f04", None),
    # Georgia
    ("Georgia", "Ja'Marley Riddle", None, "0cb0d792-32ba-4583-a873-500fab8913de", None),
    # Iowa
    ("Iowa", "Carson Nielsen", None, "de6c909a-0804-48cd-bc6b-ffda71680225", None),
    # LSU
    ("LSU", "Princewill Umanmielen", None, "69bd27c9-990f-40a4-9182-1e4f84f1cd23", None),
    ("LSU", "Sam Leavitt", None, "4c809c4d-cf25-4965-be9c-f044f3d168ee", None),
    ("LSU", "DJ Pickett", "ac6af1b1-829b-4caf-95cb-413958b183c1", "8c2c359e-6550-498f-920c-782b8918a40f", {"star_rating": 5}),
    # Miami
    ("Miami", "Darian Mensah", None, "fab3b067-e567-4724-adc4-1d8a3cd57351", None),
    # Michigan
    ("Michigan", "Bryce Underwood", None, "8f5b170c-e640-4eab-af16-3bdb8e22930a", None),
    # Missouri
    ("Missouri", "Nick Evers", None, "acc144de-d492-4037-b49d-0bf1870f3ce7", None),
    # Nebraska
    ("Nebraska", "Anthony Colandrea", None, "e2011d45-0282-4f3a-930c-da4f58b3bf8f", None),
    ("Nebraska", "Claude Mpouma", None, "0ee4e7af-646d-4fa7-94bd-ac93a88755d5", None),
    # Ohio State
    ("Ohio State", "Tavien St. Clair", "bf7779f5-c9c7-4721-aad4-4adc8a601b71", "2ce7032f-d787-4245-b592-36243a2bdb3c", {"star_rating": 5}),
    ("Ohio State", "Jeremiah Smith", None, "b93ca4da-67ee-4be7-bac6-187506faafd9", None),
    ("Ohio State", "Devin Sanchez", "edf9f361-ebc5-4b81-a8a5-5c1cea41ab2c", "8f30a35f-f6be-47c4-b29f-8104a9d80d46", {"star_rating": 5}),
    # Oregon
    ("Oregon", "Anthony Jones", None, "05bdbf6e-6e38-5c0f-a2b0-2e6680fe87fc", None),
    ("Oregon", "Dylan Raiola", None, "7f686a12-687e-433d-b889-3136fdbca849", None),
    ("Oregon", "Dakorien Moore", None, "f0ae9a89-a8c4-4157-9fd5-6a944c1d5e9e", None),
    ("Oregon", "Evan Stewart", None, "80f42a8f-9b0d-4fbd-a77a-6f7a53d6b5d8", None),
    # Penn State
    ("Penn State", "Jackson Ford", None, "81082a2a-2989-40ab-8701-394e15de6d0c", None),
    # Rutgers
    ("Rutgers", "Wydeek Collier", "93351d41-7908-4583-8da7-d295a100af97", "b72a38d5-d237-4236-8a93-af07f7b317d4", {"espn_athlete_id": 5211739}),
    ("Rutgers", "Rinaldo Callaway", None, "870c9517-efb9-48bc-bd17-1e832fe0e2e9", None),
    # SMU
    ("SMU", "Jarvis Lee", None, "c4fd5bbe-98bb-49ee-80ba-0e1246d073a4", None),
    ("SMU", "Yannick Smith", None, "e1156d19-8b15-4b20-885d-4cc0eaad4e8f", None),
    ("SMU", "Drew Evers", "d6cdff93-0471-40d3-b5d2-f39bfc8d7260", "aa1a448a-37ac-523e-b5ac-e109fc0d5bf1", {"star_rating": 4}),
    ("SMU", "Jimmy Wyrick", None, "86c853ee-c5fb-4954-a555-9a98cecafbc1", None),
    # Tennessee
    ("Tennessee", "Chaz Coleman", None, "bf0b29d8-8fb9-489e-9476-d6efbed9a447", None),
    ("Tennessee", "Tevis Metcalf", "1b02ba5c-37af-45c0-8780-9174f2335d80", "5f34afe2-4791-476c-9a0d-d6417af3ed28", {"total_followers": 11293}),
    ("Tennessee", "Tk Keys", "d7e3e9c6-8f40-4ddf-8500-05fb7f4a1470", "955b6284-71db-5611-89ab-5d57d5cb1aad", {"star_rating": 5}),
    ("Tennessee", "Jadais Richard", None, "a022e0c6-2c7b-49af-9695-a8ccc37e38ea", None),
    ("Tennessee", "Javin Gordon", None, "49b41a3a-ed09-4276-a63e-b2b03a59ca4f", None),
    ("Tennessee", "Ian Duarte", None, "1c42dbb2-32ce-4c69-a7f6-12465f8a3191", None),
    ("Tennessee", "Jordan Norman", "2ca409f7-e07a-43fb-83c5-f1f897dca3aa", "facbc965-732a-4829-b8e2-6b0f90c01143", {"total_followers": 4104}),
    ("Tennessee", "DJ Burks", None, "1878694c-28bc-4a00-8288-2f9482ad3a6e", None),
    ("Tennessee", "Blake Howard", None, "22434edf-75a8-4307-8acf-7adff662f975", None),
    # Texas
    ("Texas", "Cam Coleman", None, "0f9934eb-44eb-47c4-8816-a6b465647be8", None),
    ("Texas", "Colin Simmons", None, "accf0543-96f7-4db6-887d-88c81f2e9a62", None),
    # Texas A&M
    ("Texas A&M", "Taurean York", None, "32bd58e5-c0e0-4bd2-968e-14166d9457b8", None),
    ("Texas A&M", "Terry Bussey", "e6300eb9-c413-4a0b-ad64-a45f7d50a99b", "8df3307e-397a-490d-adb2-1834e9eeea7d", {"total_followers": 35162}),
    ("Texas A&M", "KC Concepcion", None, "38b372b0-a7e7-4356-a5eb-3737687016f0", None),
    # USC
    ("USC", "Elbert Hill IV", None, "2f575cf2-0c89-4b92-8329-5ed12d4ce098", None),
    # Washington
    ("Washington", "Brian Bonner", None, "76b46463-2e58-5573-841c-7e63359a2898", None),
    ("Washington", "Jordan Washington #1", "e8d14430-b81a-4bff-9390-3610c84954c6", "85bfc51f-0a56-4454-976b-59b35dba9976", {"cfbd_id": 5219119, "ea_rating": 79, "production_score": 59.5, "star_rating": 4}),
    ("Washington", "Jordan Washington #2", "e8d14430-b81a-4bff-9390-3610c84954c6", "7510ea83-73c8-42f5-9755-1fb4d03089b2", {"cfbd_id": 5146756, "production_score": 63.5, "star_rating": 4, "total_followers": 4553}),
]


def main():
    print("=" * 70)
    print("  EXECUTING DUPLICATE CLEANUP")
    print("=" * 70)

    merged = 0
    deleted = 0
    errors = 0

    # Phase 1: Merges (UPDATE keeper with stale's useful fields)
    print("\n  Phase 1: Merging useful fields into keepers...")
    for team, name, keeper_id, delete_id, merge_fields in CLEANUP_PLAN:
        if merge_fields and keeper_id:
            try:
                supabase.table("players").update(merge_fields).eq("id", keeper_id).execute()
                print(f"    [MERGED] {team}: {name} -- {merge_fields}")
                merged += 1
            except Exception as exc:
                print(f"    [ERROR] {team}: {name} merge failed -- {exc}")
                errors += 1

    # Phase 2: Deletes
    print(f"\n  Phase 2: Deleting {len(CLEANUP_PLAN)} stale records...")
    for team, name, keeper_id, delete_id, merge_fields in CLEANUP_PLAN:
        try:
            supabase.table("players").delete().eq("id", delete_id).execute()
            print(f"    [DELETED] {team}: {name} (id={delete_id[:12]}...)")
            deleted += 1
        except Exception as exc:
            print(f"    [ERROR] {team}: {name} delete failed -- {exc}")
            errors += 1

    # Phase 3: Verify
    print(f"\n  Phase 3: Verifying no remaining duplicates...")
    all_p = []
    offset = 0
    while True:
        resp = (
            supabase.table("players")
            .select("id, name, team_id, player_tag")
            .range(offset, offset + 999)
            .execute()
        )
        batch = resp.data or []
        all_p.extend(batch)
        if len(batch) < 1000:
            break
        offset += 1000

    from collections import defaultdict
    import re, unicodedata

    def normalize(n):
        if not n: return ""
        n = unicodedata.normalize("NFKD", n).encode("ascii", "ignore").decode("ascii")
        n = re.sub(r"\b(jr\.?|sr\.?|ii|iii|iv|v)\b", n.lower().strip(), "")
        n = n.replace(".", "").replace("'", "").replace("-", " ")
        return " ".join(n.split())

    groups = defaultdict(list)
    for p in all_p:
        key = (p.get("team_id") or "", normalize(p.get("name", "")))
        groups[key].append(p)

    remaining = {k: v for k, v in groups.items() if len(v) > 1}

    print(f"\n{'=' * 70}")
    print(f"  CLEANUP COMPLETE")
    print(f"{'=' * 70}")
    print(f"  Merges executed:       {merged}")
    print(f"  Records deleted:       {deleted}")
    print(f"  Errors:                {errors}")
    print(f"  Remaining duplicates:  {len(remaining)}")

    if remaining:
        print(f"\n  WARNING: {len(remaining)} duplicate group(s) still remain:")
        for (tid, norm), group in remaining.items():
            names = [p["name"] for p in group]
            print(f"    {names[0]} ({len(group)} records)")
    else:
        print(f"\n  All duplicates resolved. Database is clean.")

    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
