ALTER TABLE teams ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
ALTER TABLE players ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_teams_slug ON teams(slug) WHERE slug IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_players_slug ON players(slug) WHERE slug IS NOT NULL;
